version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk17
    commands:
      # Install Docker
      - echo Installing Docker...
      - yum install -y docker
      - service docker start
      - docker info
      - echo Installing Amazon Corretto 17...
      - curl -O https://corretto.aws/downloads/latest/amazon-corretto-17-x86_64-linux-jdk.rpm
      - yum localinstall -y amazon-corretto-17-x86_64-linux-jdk.rpm

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=886436972291.dkr.ecr.ap-south-1.amazonaws.com/spring-message-app
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Building the Spring Boot application...
      - mvn clean install -DskipTests
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
